mutation setRelayInformation($pubkey: String, $contact: String, $name: String, $description: String, $icon: String) {
  set_relay_information(
    pubkey: $pubkey
    contact: $contact
    name: $name
    description: $description
    icon: $icon
  ) {
    name
    contact
    description
    icon
    pubkey {
      hex
      bech32
    }
    software
    supported_nips
    version
  }
}
